on:
  push:
    tags:
      - "v*.*.*"

name: Build and Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Install Python
        id: install_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        id: install_dependencies
        run: |
          python3 -m pip install --user --upgrade setuptools wheel twine

      - name: Build
        id: build
        run: |
          python3 setup.py sdist bdist_wheel

      - name: Publish
        id: publish
        run: |
          python3 -m twine upload --repository crisp-api dist/*
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY_URL: "https://upload.pypi.org/legacy/"
